export const USER_LOGIN_REQUEST = 'USER_LOGIN-REQUEST'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN-SUCCESS'
export const USER_LOGIN_FAIL = 'USER_LOGIN-FAIL'
export const USER_LOGOUT = 'USER_LOGOUT'


export const USER_REGISTER_REQUEST = 'USER_REGISTER-REQUEST'
export const USER_REGISTER_SUCCESS = 'USER_REGISTER-SUCCESS'
export const USER_REGISTER_FAIL = 'USER_REGISTER-FAIL'


export const USER_DETAILS_REQUEST = 'USER_DETAILS-REQUEST'
export const USER_DETAILS_SUCCESS = 'USER_DETAILS-SUCCESS'
export const USER_DETAILS_FAIL = 'USER_DETAILS-FAIL'


export const USER_UPDATE_PROFILE_REQUEST = 'USER_UPDATE_PROFILE-REQUEST'
export const USER_UPDATE_PROFILE_SUCCESS = 'USER_UPDATE_PROFILE-SUCCESS'
export const USER_UPDATE_PROFILE_FAIL = 'USER_UPDATE_PROFILE-FAIL'
export const USER_UPDATE_PROFILE_RESET = 'USER_UPDATE_PROFILE-RESET'



